###################################
#
# make start-all
#
# docker exec -it wavs bash
#
###################################

services:
  wavs:
    image: "ghcr.io/lay3rlabs/wavs:0.4.0-beta.5"
    container_name: "wavs"
    stop_signal: SIGKILL
    network_mode: "host"
    env_file: "./.env"
    ports:
      - "8000:8000"
    environment:
      WAVS_HOME: "/wavs/packages/wavs"
      WAVS_CLI_HOME: "/wavs/packages/cli"
      WAVS_AGGREGATOR_HOME: "/wavs/packages/aggregator"
    command: ["wavs"]
    volumes:
      - "./:/wavs"
      - "./.docker:/root/wavs/cli/"

  aggregator:
    image: "ghcr.io/lay3rlabs/wavs:0.4.0-beta.5"
    depends_on: ["wavs"]
    container_name: "wavs-aggregator"
    stop_signal: SIGKILL
    env_file: "./.env"
    ports:
      - "8001:8001"
    command: ["wavs-aggregator"]
    volumes:
      - ".:/wavs"
    network_mode: "host"

  ipfs:
    image: "ipfs/kubo:v0.34.1"
    container_name: "ipfs"
    stop_signal: SIGKILL
    network_mode: "host"
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"
    command: ["daemon", "--offline"]

  # Default all-memory Jaeger
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    network_mode: "host"
    stop_signal: SIGKILL
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4317:4317" # OTLP gRPC
      - "16686:16686" # Jaeger UI

  # Prometheus is used to display metrics
  prometheus:
    image: prom/prometheus:v3.3.0
    network_mode: "host"
    stop_signal: SIGKILL
    ports:
      - "9090:9090" # Prometheus UI and OTLP receiver
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-otlp-receiver"
