###################################
#
# make start-all
#
# docker exec -it wavs bash
#
###################################

services:
  wavs:
    image: "ghcr.io/lay3rlabs/wavs:reece_priv_key_signing_apr_10"
    container_name: "wavs"
    stop_signal: SIGKILL
    network_mode: "host"
    env_file: "./.env"
    ports:
      - "8000:8000"
    environment:
      WAVS_HOME: "/wavs/packages/wavs"
      WAVS_CLI_HOME: "/wavs/packages/cli"
      WAVS_AGGREGATOR_HOME: "/wavs/packages/aggregator"
    command: ["wavs"]
    volumes:
      - "./:/wavs"
      - "./.docker:/root/wavs/cli/"

  aggregator:
    image: "ghcr.io/lay3rlabs/wavs:reece_priv_key_signing_apr_10"
    depends_on: ["wavs"] # "anvil",
    container_name: "wavs-aggregator"
    stop_signal: SIGKILL
    env_file: "./.env"
    ports:
      - "8001:8001"
    command: ["wavs-aggregator"]
    volumes:
      - ".:/wavs"
    network_mode: "host"
