#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod addressupgradeable;
pub mod checkpointsupgradeable;
pub mod contextupgradeable;
pub mod ecdsaservicemanagerbase;
pub mod ecdsastakeregistry;
pub mod ecdsastakeregistryeventsanderrors;
pub mod ecdsastakeregistrystorage;
pub mod ecdsaupgradeable;
pub mod iavsdirectory;
pub mod idelegationmanager;
pub mod ierc1271upgradeable;
pub mod ierc20;
pub mod ilayerservicehandler;
pub mod ilayerservicemanager;
pub mod initializable;
pub mod iregistry;
pub mod irewardscoordinator;
pub mod iservicemanager;
pub mod iservicemanagerui;
pub mod isignatureutils;
pub mod isimplesubmit;
pub mod isimpletrigger;
pub mod istakeregistry;
pub mod istrategy;
pub mod iwavsservice;
pub mod layerservicemanager;
pub mod mathupgradeable;
pub mod ownableupgradeable;
pub mod safecastupgradeable;
pub mod signaturecheckerupgradeable;
pub mod simplesubmit;
pub mod simpletrigger;
pub mod strings;
pub mod stringsupgradeable;
pub mod wavssubmit;
