name: E2E

# based on https://docs.wavs.xyz/ & this repos README.md

on:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DEBUGGING: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ubuntu packages
      run: sudo apt-get install bash make jq

    - uses: actions/setup-node@v4
      name: Install Node.js
      with:
        node-version: 21

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2
      name: Cache Cargo dependencies
      with:
        cache-on-failure: true

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install rust wasm32-wasip2
      run: |
        rustup update stable
        rustup target add wasm32-wasip2

    # move to `- uses: cargo-bins/cargo-binstall@main` ?
    - name: Install wasi components
      run: |
        cargo install cargo-component warg-cli wkg --locked
        wkg config --default-registry wa.dev

    - name: Install forge deps
      run: make setup

    - name: build contracts
      run: forge build

    - name: wasi build and local exec
      run: |
        make wasi-build
        make wasi-exec

    # TODO: https://github.com/peter-evans/docker-compose-actions-workflow
    # modified version of `make start-all`
    - name: Build the stack
      run: |
        anvil --host 0.0.0.0 &
        docker compose up -d

    - name: Run tests
      run: |
        make deploy-contracts
        sleep 2
        TRIGGER_EVENT="NewTrigger(bytes)" make deploy-service
        sleep 2
        COIN_MARKET_CAP_ID=1 make trigger-service
        sleep 2

    - name: Run show result
      run: make show-result

    - name: Stop the stack
      run: |
        killall anvil
        docker compose down
