name: Check WAVS Image Version

on:
  pull_request:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    env:
      DEBUGGING: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install bash
      run: sudo apt-get install bash

    - name: Make script executable
      run: chmod +x .github/single-wavs-image-verifier.bash

    - name: Run script
      run: bash .github/single-wavs-image-verifier.bash
